-- ============================================================
-- 20260732_a2p_fee_correction.sql
-- Correct the A2P 10DLC pass-through fee defaults to Telnyx's real prices.
--
-- SOURCE: Telnyx's own checkout, read by Jace on 2026-07-28. Not a published
-- price page, not an inference from an invoice — the number on the screen at
-- the point of purchase. Campaign pricing:
--
--     $10.00   application fee            one-off, at submission
--      $4.50   first 3 months             one-off, at submission (3 x $1.50)
--      $1.50   per month thereafter       recurring
--                                          3-month minimum term
--
-- WHAT WAS WRONG
-- --------------
--   a2p_campaign_fee_mills   15000  ($15.00)  -> 14500  ($14.50)
--   a2p_monthly_fee_mills    10000  ($10.00)  ->  1500   ($1.50)
--
-- The monthly was ~6.7x the real price. These are PASS-THROUGH figures shown
-- to and recorded against agents, so an inflated default is not a cosmetic
-- error: a2p-register stamps monthly_fee_mills onto every a2p_registrations
-- row at submission, and that number is what any later reconciliation or
-- agent-facing statement would be built from.
--
-- $14.50 is deliberately ONE column, not two. Telnyx bills the $10.00
-- application fee and the $4.50 first-quarter together at submission, and the
-- existing flow debits the campaign fee exactly once at that moment (see
-- _shared/a2p-registration.ts STEP 5), so a single figure matches both what
-- Telnyx charges us and when. Splitting it would add a column nothing reads.
--
-- NOT CHANGED, deliberately:
--   a2p_brand_fee_mills (4000, $4.00)
--       Brand registration, unchanged and not part of the checkout above.
--   a2p_sole_prop_monthly_fee_mills (2000, $2.00)
--       The checkout Jace read did not identify a brand type. $2.00/mo comes
--       from Telnyx's published SOLE PROPRIETOR pricing (PROMPT_15 §2.1) and
--       sole-prop campaigns are priced separately from standard ones. Moving
--       it to $1.50 on the assumption the two are the same would be inventing
--       a price. Left as-is and flagged in docs/schema-state.md — confirm
--       against a sole-prop checkout, then correct it in its own migration.
--
-- STILL TRUE AFTER THIS FILE: **nothing ever debits the monthly fee.** It is
-- read, stamped onto the registration row and echoed in the API response, and
-- that is all — no wallet_debit, no cron, anywhere. Correcting the number does
-- not start charging it. PROMPT_15's "Fee reconciliation" item is still open;
-- the recurring cost is absorbed on every agent. See docs/schema-state.md.
--
-- HOW TO APPLY: `supabase db query --linked -f <this file>`, transaction-
-- wrapped, per docs/schema-state.md. Idempotent — re-running is a no-op.
-- No DDL beyond ALTER COLUMN SET DEFAULT and COMMENT; no DROP, no data loss,
-- nothing touching auth.* or storage.*. The single UPDATE targets the one
-- config singleton row (id = 1) and is authorised by Jace, 2026-07-28.
--
-- A LATER GENUINE PRICE CHANGE GETS ITS OWN MIGRATION. Do not edit this file
-- to track a new price — that would silently rewrite history for anyone
-- replaying it.
-- ============================================================

do $$
begin
  if to_regclass('public.billing_config') is null then
    raise notice '[20260732] public.billing_config is missing — apply data/sql/016_wallet_foundation.sql first. Skipping.';
  else
    -- 1. Column defaults, so a fresh install starts correct.
    alter table public.billing_config
      alter column a2p_campaign_fee_mills set default 14500,
      alter column a2p_monthly_fee_mills  set default 1500;

    comment on column public.billing_config.a2p_campaign_fee_mills is
      'One-off Telnyx 10DLC campaign cost debited at submission: $10.00 application fee + $4.50 prepaid first 3 months = $14.50 (14500 mills). Source: Telnyx checkout, 2026-07-28. Telnyx bills both together at submission, which is why this is one figure and not two.';
    comment on column public.billing_config.a2p_monthly_fee_mills is
      'Recurring Telnyx 10DLC campaign fee for a STANDARD brand: $1.50/month (1500 mills), starting after the prepaid first 3 months, 3-month minimum term. Source: Telnyx checkout, 2026-07-28 (was 10000 = $10.00, ~6.7x too high). NOTE: nothing in the codebase debits this today — it is stamped onto a2p_registrations.monthly_fee_mills and echoed in API responses only.';
    comment on column public.billing_config.a2p_sole_prop_monthly_fee_mills is
      'Recurring Telnyx 10DLC campaign fee for a SOLE PROPRIETOR brand: $2.00/month (2000 mills), from Telnyx published sole-prop pricing (PROMPT_15 §2.1). UNVERIFIED against a live sole-prop checkout — the 2026-07-28 checkout that corrected the standard prices did not identify a brand type. Confirm before relying on it.';

    -- 2. The live singleton. Set unconditionally: this migration asserts the
    --    correct price rather than patching one specific wrong value, so it
    --    converges from whatever is currently there.
    update public.billing_config
       set a2p_campaign_fee_mills = 14500,
           a2p_monthly_fee_mills  = 1500
     where id = 1;

    raise notice '[20260732] A2P fees corrected: campaign 15000 -> 14500 mills, monthly 10000 -> 1500 mills.';
  end if;
end $$;

-- ------------------------------------------------------------
-- Verify after running:
--
--   select a2p_brand_fee_mills, a2p_campaign_fee_mills,
--          a2p_monthly_fee_mills, a2p_sole_prop_monthly_fee_mills
--     from public.billing_config where id = 1;
--   -- expect 4000 | 14500 | 1500 | 2000
--
--   select column_name, column_default from information_schema.columns
--    where table_name = 'billing_config' and column_name like 'a2p_%';
--   -- expect campaign 14500, monthly 1500
-- ------------------------------------------------------------
